<?php

namespace Database\Seeders;

use App\Models\Resident;
use App\Models\Branch;
use Illuminate\Database\Seeder;

class ResidentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $branches = Branch::active()->get();
        
        if ($branches->isEmpty()) {
            $this->command->warn('No branches found. Please run BranchSeeder first.');
            return;
        }

        $residents = [
            [
                'name' => 'Margaret Thompson',
                'first_name' => 'Margaret',
                'middle_names' => 'Elizabeth',
                'last_name' => 'Thompson',
                'date_of_birth' => '1935-03-15',
                'diagnosis' => 'Type 2 Diabetes with Hypertension',
                'allergies' => 'Penicillin, Shellfish',
                'physician_name' => 'Dr. Sarah Johnson',
                'pep_or_doctor' => 'Dr. Michael Chen (Endocrinologist)',
                'room_number' => '101',
                'cart' => 'Cart A-101',
                'admission_date' => '2023-01-10',
                'medical_conditions' => 'Diabetes, Hypertension',
                'emergency_contact_name' => 'John Thompson',
                'emergency_contact_phone' => '(425) 555-1001',
                'notes' => 'Prefers morning walks and enjoys classical music.',
                'is_active' => true,
            ],
            [
                'name' => 'Alice Williams',
                'first_name' => 'Alice',
                'middle_names' => 'Grace',
                'last_name' => 'Williams',
                'date_of_birth' => '1933-06-20',
                'diagnosis' => 'Osteoarthritis with Chronic Pain',
                'allergies' => 'Aspirin, Latex',
                'physician_name' => 'Dr. Robert Kim',
                'pep_or_doctor' => 'Dr. Lisa Park (Rheumatologist)',
                'room_number' => '102',
                'cart' => 'Cart A-102',
                'admission_date' => '2023-01-25',
                'medical_conditions' => 'Osteoarthritis, Chronic pain, Mobility issues',
                'emergency_contact_name' => 'James Williams',
                'emergency_contact_phone' => '(425) 555-1011',
                'notes' => 'Former nurse, very knowledgeable about medications. Enjoys knitting.',
                'is_active' => true,
            ],
            [
                'name' => 'Harold Smith',
                'first_name' => 'Harold',
                'middle_names' => 'James',
                'last_name' => 'Smith',
                'date_of_birth' => '1940-09-12',
                'diagnosis' => 'Congestive Heart Failure',
                'allergies' => 'None known',
                'physician_name' => 'Dr. Maria Rodriguez',
                'pep_or_doctor' => 'Dr. David Lee (Cardiologist)',
                'room_number' => '103',
                'cart' => 'Cart A-103',
                'admission_date' => '2023-02-08',
                'medical_conditions' => 'Heart failure, Fluid retention, Fatigue',
                'emergency_contact_name' => 'Betty Smith',
                'emergency_contact_phone' => '(425) 555-1012',
                'notes' => 'Former mechanic, loves tinkering with small projects. Needs low-sodium diet.',
                'is_active' => true,
            ],
            [
                'name' => 'Edna Johnson',
                'first_name' => 'Edna',
                'middle_names' => 'Marie',
                'last_name' => 'Johnson',
                'date_of_birth' => '1931-12-03',
                'diagnosis' => 'Alzheimer\'s Disease - Early Stage',
                'allergies' => 'Sulfa drugs',
                'physician_name' => 'Dr. Jennifer White',
                'pep_or_doctor' => 'Dr. Thomas Brown (Neurologist)',
                'room_number' => '104',
                'cart' => 'Cart A-104',
                'admission_date' => '2023-02-20',
                'medical_conditions' => 'Alzheimer\'s, Memory loss, Confusion',
                'emergency_contact_name' => 'Robert Johnson Jr.',
                'emergency_contact_phone' => '(425) 555-1013',
                'notes' => 'Very sweet lady, responds well to familiar faces. Enjoys music from the 1950s.',
                'is_active' => true,
            ],
            [
                'name' => 'Walter Davis',
                'first_name' => 'Walter',
                'middle_names' => 'Franklin',
                'last_name' => 'Davis',
                'date_of_birth' => '1938-04-18',
                'diagnosis' => 'Chronic Obstructive Pulmonary Disease (COPD)',
                'allergies' => 'Dust mites, Pollen',
                'physician_name' => 'Dr. Amanda Clark',
                'pep_or_doctor' => 'Dr. Kevin Wilson (Pulmonologist)',
                'room_number' => '105',
                'cart' => 'Cart A-105',
                'admission_date' => '2023-03-05',
                'medical_conditions' => 'COPD, Shortness of breath, Chronic cough',
                'emergency_contact_name' => 'Linda Davis',
                'emergency_contact_phone' => '(425) 555-1014',
                'notes' => 'Former teacher, loves reading. Needs oxygen therapy. Very independent.',
                'is_active' => true,
            ],
            [
                'name' => 'Florence Brown',
                'first_name' => 'Florence',
                'middle_names' => 'Rose',
                'last_name' => 'Brown',
                'date_of_birth' => '1936-11-25',
                'diagnosis' => 'Rheumatoid Arthritis with Joint Deformities',
                'allergies' => 'NSAIDs, Shellfish',
                'physician_name' => 'Dr. Patricia Taylor',
                'pep_or_doctor' => 'Dr. Susan Garcia (Rheumatologist)',
                'room_number' => '106',
                'cart' => 'Cart A-106',
                'admission_date' => '2023-03-18',
                'medical_conditions' => 'Rheumatoid arthritis, Joint pain, Stiffness',
                'emergency_contact_name' => 'Michael Brown',
                'emergency_contact_phone' => '(425) 555-1015',
                'notes' => 'Former seamstress, still enjoys hand crafts. Needs assistance with fine motor tasks.',
                'is_active' => true,
            ],
            [
                'name' => 'Arthur Wilson',
                'first_name' => 'Arthur',
                'middle_names' => 'Charles',
                'last_name' => 'Wilson',
                'date_of_birth' => '1934-07-30',
                'diagnosis' => 'Parkinson\'s Disease with Tremors',
                'allergies' => 'None known',
                'physician_name' => 'Dr. Richard Anderson',
                'pep_or_doctor' => 'Dr. Nancy Davis (Neurologist)',
                'room_number' => '107',
                'cart' => 'Cart A-107',
                'admission_date' => '2023-04-02',
                'medical_conditions' => 'Parkinson\'s, Tremors, Balance issues, Slow movements',
                'emergency_contact_name' => 'Carol Wilson',
                'emergency_contact_phone' => '(425) 555-1016',
                'notes' => 'Former engineer, very methodical. Enjoys puzzles and chess. Needs medication timing.',
                'is_active' => true,
            ],
            [
                'name' => 'Mildred Miller',
                'first_name' => 'Mildred',
                'middle_names' => 'Jane',
                'last_name' => 'Miller',
                'date_of_birth' => '1932-02-14',
                'diagnosis' => 'Stroke with Left-Side Weakness',
                'allergies' => 'Penicillin',
                'physician_name' => 'Dr. Christopher Lee',
                'pep_or_doctor' => 'Dr. Rachel Green (Physical Therapist)',
                'room_number' => '108',
                'cart' => 'Cart A-108',
                'admission_date' => '2023-04-15',
                'medical_conditions' => 'Stroke, Left-side weakness, Speech difficulties',
                'emergency_contact_name' => 'William Miller',
                'emergency_contact_phone' => '(425) 555-1017',
                'notes' => 'Making good progress with physical therapy. Very determined and positive attitude.',
                'is_active' => true,
            ],
            [
                'name' => 'Eugene Garcia',
                'first_name' => 'Eugene',
                'middle_names' => 'Manuel',
                'last_name' => 'Garcia',
                'date_of_birth' => '1939-10-08',
                'diagnosis' => 'Type 1 Diabetes with Complications',
                'allergies' => 'Latex, Sulfa',
                'physician_name' => 'Dr. Lisa Martinez',
                'pep_or_doctor' => 'Dr. Carlos Rodriguez (Endocrinologist)',
                'room_number' => '109',
                'cart' => 'Cart A-109',
                'admission_date' => '2023-05-01',
                'medical_conditions' => 'Type 1 Diabetes, Diabetic neuropathy, Vision problems',
                'emergency_contact_name' => 'Maria Garcia',
                'emergency_contact_phone' => '(425) 555-1018',
                'notes' => 'Former chef, still loves cooking. Needs strict blood sugar monitoring.',
                'is_active' => true,
            ],
            [
                'name' => 'Dorothy Anderson',
                'first_name' => 'Dorothy',
                'middle_names' => 'Louise',
                'last_name' => 'Anderson',
                'date_of_birth' => '1937-05-22',
                'diagnosis' => 'Osteoporosis with Multiple Fractures',
                'allergies' => 'Bisphosphonates',
                'physician_name' => 'Dr. Michelle Thompson',
                'pep_or_doctor' => 'Dr. James Wilson (Orthopedist)',
                'room_number' => '110',
                'cart' => 'Cart A-110',
                'admission_date' => '2023-05-20',
                'medical_conditions' => 'Osteoporosis, Previous fractures, Fall risk',
                'emergency_contact_name' => 'Frank Anderson',
                'emergency_contact_phone' => '(425) 555-1019',
                'notes' => 'Very careful about falls. Enjoys gentle exercises and reading.',
                'is_active' => true,
            ],
            [
                'name' => 'Robert Johnson',
                'first_name' => 'Robert',
                'last_name' => 'Johnson',
                'date_of_birth' => '1940-07-22',
                'room_number' => '102',
                'admission_date' => '2023-02-15',
                'medical_conditions' => 'Arthritis, Heart condition',
                'emergency_contact_name' => 'Mary Johnson',
                'emergency_contact_phone' => '(425) 555-1002',
                'notes' => 'Former teacher, loves reading and crossword puzzles.',
                'is_active' => true,
            ],
            [
                'name' => 'Eleanor Davis',
                'first_name' => 'Eleanor',
                'last_name' => 'Davis',
                'date_of_birth' => '1932-11-08',
                'room_number' => '103',
                'admission_date' => '2023-03-20',
                'medical_conditions' => 'Dementia, Mobility issues',
                'emergency_contact_name' => 'Sarah Davis',
                'emergency_contact_phone' => '(425) 555-1003',
                'notes' => 'Requires assistance with daily activities. Enjoys gardening.',
                'is_active' => true,
            ],
            [
                'name' => 'William Brown',
                'first_name' => 'William',
                'last_name' => 'Brown',
                'date_of_birth' => '1938-05-12',
                'room_number' => '201',
                'admission_date' => '2023-04-05',
                'medical_conditions' => 'Parkinson\'s disease',
                'emergency_contact_name' => 'Linda Brown',
                'emergency_contact_phone' => '(425) 555-1004',
                'notes' => 'Needs medication reminders. Enjoys watching sports.',
                'is_active' => true,
            ],
            [
                'name' => 'Dorothy Wilson',
                'first_name' => 'Dorothy',
                'last_name' => 'Wilson',
                'date_of_birth' => '1934-09-30',
                'room_number' => '202',
                'admission_date' => '2023-05-12',
                'medical_conditions' => 'Osteoporosis, Vision impairment',
                'emergency_contact_name' => 'Michael Wilson',
                'emergency_contact_phone' => '(425) 555-1005',
                'notes' => 'Very social, loves group activities and crafts.',
                'is_active' => true,
            ],
            [
                'name' => 'Charles Miller',
                'first_name' => 'Charles',
                'last_name' => 'Miller',
                'date_of_birth' => '1942-01-18',
                'room_number' => '203',
                'admission_date' => '2023-06-08',
                'medical_conditions' => 'COPD, Depression',
                'emergency_contact_name' => 'Jennifer Miller',
                'emergency_contact_phone' => '(425) 555-1006',
                'notes' => 'Former engineer, enjoys puzzles and quiet activities.',
                'is_active' => true,
            ],
            [
                'name' => 'Helen Garcia',
                'first_name' => 'Helen',
                'last_name' => 'Garcia',
                'date_of_birth' => '1936-12-03',
                'room_number' => '301',
                'admission_date' => '2023-07-15',
                'medical_conditions' => 'Alzheimer\'s, Mobility assistance needed',
                'emergency_contact_name' => 'Carlos Garcia',
                'emergency_contact_phone' => '(425) 555-1007',
                'notes' => 'Bilingual, responds well to music therapy.',
                'is_active' => true,
            ],
            [
                'name' => 'Frank Anderson',
                'first_name' => 'Frank',
                'last_name' => 'Anderson',
                'date_of_birth' => '1939-08-25',
                'room_number' => '302',
                'admission_date' => '2023-08-22',
                'medical_conditions' => 'Heart disease, Diabetes',
                'emergency_contact_name' => 'Patricia Anderson',
                'emergency_contact_phone' => '(425) 555-1008',
                'notes' => 'Former chef, enjoys cooking demonstrations.',
                'is_active' => true,
            ],
            [
                'name' => 'Ruth Taylor',
                'first_name' => 'Ruth',
                'last_name' => 'Taylor',
                'date_of_birth' => '1937-04-14',
                'room_number' => '303',
                'admission_date' => '2023-09-10',
                'medical_conditions' => 'Stroke recovery, Speech therapy',
                'emergency_contact_name' => 'David Taylor',
                'emergency_contact_phone' => '(425) 555-1009',
                'notes' => 'Making good progress with speech therapy.',
                'is_active' => true,
            ],
            [
                'name' => 'George Martinez',
                'first_name' => 'George',
                'last_name' => 'Martinez',
                'date_of_birth' => '1941-10-07',
                'room_number' => '401',
                'admission_date' => '2023-10-05',
                'medical_conditions' => 'Kidney disease, High blood pressure',
                'emergency_contact_name' => 'Ana Martinez',
                'emergency_contact_phone' => '(425) 555-1010',
                'notes' => 'Needs regular dialysis. Enjoys watching movies.',
                'is_active' => true,
            ],
            [
                'name' => 'Beatrice Taylor',
                'first_name' => 'Beatrice',
                'middle_names' => 'Ann',
                'last_name' => 'Taylor',
                'date_of_birth' => '1935-08-15',
                'diagnosis' => 'Macular Degeneration with Vision Loss',
                'allergies' => 'None known',
                'physician_name' => 'Dr. Sarah Chen',
                'pep_or_doctor' => 'Dr. Michael Wong (Ophthalmologist)',
                'room_number' => '111',
                'cart' => 'Cart A-111',
                'admission_date' => '2023-06-10',
                'medical_conditions' => 'Macular degeneration, Vision loss, Mobility challenges',
                'emergency_contact_name' => 'Robert Taylor',
                'emergency_contact_phone' => '(425) 555-1020',
                'notes' => 'Former librarian, loves audiobooks. Needs assistance with reading and navigation.',
                'is_active' => true,
            ],
            [
                'name' => 'Clarence White',
                'first_name' => 'Clarence',
                'middle_names' => 'Edward',
                'last_name' => 'White',
                'date_of_birth' => '1933-01-28',
                'diagnosis' => 'Dementia with Behavioral Changes',
                'allergies' => 'None known',
                'physician_name' => 'Dr. Jennifer Liu',
                'pep_or_doctor' => 'Dr. David Park (Geriatrician)',
                'room_number' => '112',
                'cart' => 'Cart A-112',
                'admission_date' => '2023-06-25',
                'medical_conditions' => 'Dementia, Confusion, Sundowning, Agitation',
                'emergency_contact_name' => 'Mary White',
                'emergency_contact_phone' => '(425) 555-1021',
                'notes' => 'Former farmer, responds well to routine. Can become agitated in the evening.',
                'is_active' => true,
            ],
            [
                'name' => 'Gladys Harris',
                'first_name' => 'Gladys',
                'middle_names' => 'May',
                'last_name' => 'Harris',
                'date_of_birth' => '1938-12-10',
                'diagnosis' => 'Chronic Kidney Disease Stage 4',
                'allergies' => 'Contrast dye',
                'physician_name' => 'Dr. Robert Johnson',
                'pep_or_doctor' => 'Dr. Lisa Wang (Nephrologist)',
                'room_number' => '113',
                'cart' => 'Cart A-113',
                'admission_date' => '2023-07-08',
                'medical_conditions' => 'Kidney disease, Fluid restrictions, Fatigue',
                'emergency_contact_name' => 'John Harris',
                'emergency_contact_phone' => '(425) 555-1022',
                'notes' => 'Former teacher, very patient. Needs strict fluid monitoring and low-protein diet.',
                'is_active' => true,
            ],
            [
                'name' => 'Raymond Clark',
                'first_name' => 'Raymond',
                'middle_names' => 'Joseph',
                'last_name' => 'Clark',
                'date_of_birth' => '1942-03-05',
                'diagnosis' => 'Prostate Cancer in Remission',
                'allergies' => 'None known',
                'physician_name' => 'Dr. Patricia Davis',
                'pep_or_doctor' => 'Dr. Kevin Lee (Oncologist)',
                'room_number' => '114',
                'cart' => 'Cart A-114',
                'admission_date' => '2023-07-22',
                'medical_conditions' => 'Cancer history, Fatigue, Weight loss, Depression',
                'emergency_contact_name' => 'Helen Clark',
                'emergency_contact_phone' => '(425) 555-1023',
                'notes' => 'Former accountant, very organized. Enjoys card games and gentle walks.',
                'is_active' => true,
            ],
            [
                'name' => 'Irene Lewis',
                'first_name' => 'Irene',
                'middle_names' => 'Rose',
                'last_name' => 'Lewis',
                'date_of_birth' => '1936-09-18',
                'diagnosis' => 'Multiple Sclerosis with Mobility Issues',
                'allergies' => 'Latex',
                'physician_name' => 'Dr. Mark Thompson',
                'pep_or_doctor' => 'Dr. Susan Kim (Neurologist)',
                'room_number' => '115',
                'cart' => 'Cart A-115',
                'admission_date' => '2023-08-05',
                'medical_conditions' => 'Multiple sclerosis, Muscle weakness, Balance problems',
                'emergency_contact_name' => 'Paul Lewis',
                'emergency_contact_phone' => '(425) 555-1024',
                'notes' => 'Former nurse, very knowledgeable about her condition. Needs mobility assistance.',
                'is_active' => true,
            ],
            [
                'name' => 'Stanley Walker',
                'first_name' => 'Stanley',
                'middle_names' => 'Ray',
                'last_name' => 'Walker',
                'date_of_birth' => '1939-06-12',
                'diagnosis' => 'Depression with Anxiety Disorder',
                'allergies' => 'SSRIs (some)',
                'physician_name' => 'Dr. Lisa Anderson',
                'pep_or_doctor' => 'Dr. Michael Brown (Psychiatrist)',
                'room_number' => '116',
                'cart' => 'Cart A-116',
                'admission_date' => '2023-08-20',
                'medical_conditions' => 'Depression, Anxiety, Sleep disturbances, Appetite changes',
                'emergency_contact_name' => 'Betty Walker',
                'emergency_contact_phone' => '(425) 555-1025',
                'notes' => 'Former mechanic, very quiet. Enjoys tinkering with small projects. Needs emotional support.',
                'is_active' => true,
            ],
            [
                'name' => 'Violet Young',
                'first_name' => 'Violet',
                'middle_names' => 'Grace',
                'last_name' => 'Young',
                'date_of_birth' => '1934-11-30',
                'diagnosis' => 'Hip Fracture with Surgical Repair',
                'allergies' => 'Morphine',
                'physician_name' => 'Dr. Jennifer White',
                'pep_or_doctor' => 'Dr. Thomas Davis (Orthopedist)',
                'room_number' => '117',
                'cart' => 'Cart A-117',
                'admission_date' => '2023-09-02',
                'medical_conditions' => 'Hip fracture, Post-surgical recovery, Physical therapy',
                'emergency_contact_name' => 'Charles Young',
                'emergency_contact_phone' => '(425) 555-1026',
                'notes' => 'Former seamstress, very determined. Making good progress with physical therapy.',
                'is_active' => true,
            ],
            [
                'name' => 'Norman Hall',
                'first_name' => 'Norman',
                'middle_names' => 'William',
                'last_name' => 'Hall',
                'date_of_birth' => '1941-04-22',
                'diagnosis' => 'Chronic Pain Syndrome',
                'allergies' => 'Opioids (some)',
                'physician_name' => 'Dr. Richard Garcia',
                'pep_or_doctor' => 'Dr. Nancy Wilson (Pain Specialist)',
                'room_number' => '118',
                'cart' => 'Cart A-118',
                'admission_date' => '2023-09-18',
                'medical_conditions' => 'Chronic pain, Sleep disturbances, Depression',
                'emergency_contact_name' => 'Ruth Hall',
                'emergency_contact_phone' => '(425) 555-1027',
                'notes' => 'Former construction worker, very strong-willed. Needs pain management and emotional support.',
                'is_active' => true,
            ],
            [
                'name' => 'Lillian King',
                'first_name' => 'Lillian',
                'middle_names' => 'Marie',
                'last_name' => 'King',
                'date_of_birth' => '1937-07-08',
                'diagnosis' => 'Heart Arrhythmia with Pacemaker',
                'allergies' => 'None known',
                'physician_name' => 'Dr. David Rodriguez',
                'pep_or_doctor' => 'Dr. Sarah Lee (Cardiologist)',
                'room_number' => '119',
                'cart' => 'Cart A-119',
                'admission_date' => '2023-10-01',
                'medical_conditions' => 'Heart arrhythmia, Pacemaker, Fatigue, Dizziness',
                'emergency_contact_name' => 'James King',
                'emergency_contact_phone' => '(425) 555-1028',
                'notes' => 'Former school principal, very organized. Needs regular pacemaker monitoring.',
                'is_active' => true,
            ],
            [
                'name' => 'Howard Wright',
                'first_name' => 'Howard',
                'middle_names' => 'Thomas',
                'last_name' => 'Wright',
                'date_of_birth' => '1935-12-14',
                'diagnosis' => 'Glaucoma with Vision Impairment',
                'allergies' => 'Eye drops (some)',
                'physician_name' => 'Dr. Patricia Chen',
                'pep_or_doctor' => 'Dr. Kevin Park (Ophthalmologist)',
                'room_number' => '120',
                'cart' => 'Cart A-120',
                'admission_date' => '2023-10-15',
                'medical_conditions' => 'Glaucoma, Vision loss, Eye pressure issues',
                'emergency_contact_name' => 'Dorothy Wright',
                'emergency_contact_phone' => '(425) 555-1029',
                'notes' => 'Former electrician, very practical. Needs assistance with reading and mobility.',
                'is_active' => true,
            ],
        ];

        foreach ($residents as $index => $residentData) {
            // Assign residents to different branches
            $branch = $branches[$index % $branches->count()];
            $residentData['branch_id'] = $branch->id;
            
            // Determine gender from name or default to 'Unknown'
            $firstName = $residentData['first_name'] ?? '';
            $gender = $residentData['gender'] ?? $this->guessGender($firstName);
            
            // Set room from room_number if room is not set
            $room = $residentData['room'] ?? $residentData['room_number'] ?? null;
            
            Resident::firstOrCreate(
                ['name' => $residentData['name'], 'branch_id' => $branch->id],
                array_merge($residentData, [
                    'gender' => $gender,
                    'room' => $room,
                    'room_number' => $residentData['room_number'] ?? $room,
                    'middle_names' => $residentData['middle_names'] ?? null,
                    'diagnosis' => $residentData['diagnosis'] ?? null,
                    'allergies' => $residentData['allergies'] ?? null,
                    'physician_name' => $residentData['physician_name'] ?? null,
                    'pep_or_doctor' => $residentData['pep_or_doctor'] ?? null,
                    'cart' => $residentData['cart'] ?? null,
                    'status' => $residentData['status'] ?? 'active',
                    'is_active' => $residentData['is_active'] ?? true,
                ])
            );
        }
        
        $this->command->info('✅ Created ' . Resident::count() . ' residents');
    }
    
    /**
     * Guess gender from common first names (simple heuristic)
     */
    private function guessGender(string $firstName): string
    {
        $femaleNames = ['Margaret', 'Alice', 'Edna', 'Florence', 'Mildred', 'Dorothy', 'Eleanor', 'Helen', 'Ruth', 'Irene', 'Violet', 'Lillian', 'Gladys', 'Beatrice'];
        $maleNames = ['Harold', 'Walter', 'Eugene', 'Arthur', 'Robert', 'William', 'Charles', 'Frank', 'George', 'Norman', 'Raymond', 'Howard', 'Clarence', 'Stanley'];
        
        if (in_array($firstName, $femaleNames)) {
            return 'Female';
        }
        if (in_array($firstName, $maleNames)) {
            return 'Male';
        }
        
        return 'Unknown';
    }
}